---
# tasks file for ansible-role-infra-init

- name: "Create swarm managers vagrant boxes"
  command: "vagrant up {{ item.cname }}"
  args:
      chdir: "{{ shelleg.vagrant_dir }}"
  with_items:
  - "{{ hosts.swarm.swarm_managers }}"
  when: (clean is undefined) or (skip_create == false)

- name: "Add swarm managers to Ansible inventory"
  add_host:
    # ansible args
    ansible_host: "{{ item.ip }}"
    ansible_port: "{{ item.ssh_port }}"
    ansible_user: "{{ item.user }}"
    # extra args
    name: "{{ item.cname }}"
    cname: "{{ item.cname }}"
    user: "{{ item.user }}"
    pass: "{{ item.pass }}"
    box: "{{ item.box }}"
    ip: "{{ item.ip }}"
    ram: "{{ item.ram }}"
    ssh_port: "{{ item.ssh_port }}"
    ansible_ssh_private_key_file: "{{ shelleg.vagrant_dir }}/.vagrant/machines/{{ item.cname }}/virtualbox/private_key"
    # hot groups
    groups: "{{ hosts.swarm.swarm_managers_group_name }},{{ hosts.swarm_group_name }}"
  with_items:
  - "{{ hosts.swarm.swarm_managers }}"

- name: "Create swarm workers vagrant boxes"
  command: "vagrant up {{ item.cname }}"
  args:
      chdir: "{{ shelleg.vagrant_dir }}"
  with_items:
  - "{{ hosts.swarm.swarm_workers }}"
  when: (clean is undefined) or (skip_create == false)

- name: "Add swarm worker nodes to Ansible inventory"
  add_host:
    # ansible args
    ansible_host: "{{ item.ip }}"
    ansible_port: "{{ item.ssh_port }}"
    ansible_user: "{{ item.user }}"
    # extra args
    name: "{{ item.cname }}"
    cname: "{{ item.cname }}"
    user: "{{ item.user }}"
    pass: "{{ item.pass }}"
    box: "{{ item.box }}"
    ip: "{{ item.ip }}"
    ram: "{{ item.ram }}"
    ssh_port: "{{ item.ssh_port }}"
    ansible_ssh_private_key_file: "{{ shelleg.vagrant_dir }}/.vagrant/machines/{{ item.cname }}/virtualbox/private_key"
    # hot groups
    groups: "{{ hosts.swarm.swarm_workers_group_name }},{{ hosts.swarm_group_name }}"
  with_items:
  - "{{ hosts.swarm.swarm_workers }}"
